#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  vm_hostname: localhost.localdomain

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    run_list:
      - recipe[apt]
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: centos-6.5
  - name: centos-7.1

suites:
  - name: lwrp_certificate
    run_list:
      - recipe[test::lwrp_certificate]
  - name: lwrp_rsa_key
    run_list:
      - recipe[test::lwrp_rsa_key]
