name 'sslcerts'
maintainer 'J. Morgan Lieberthal'
maintainer_email 'j.morgan.lieberthal@gmail.com'
license 'mit'
description 'Installs/Configures trusted ssl certs on nodes'
long_description 'Installs/Configures ssl_certs'
version '1.0.0'

depends 'chef-vault', '~> 1.3.1'
depends 'chef-sugar', '~> 3.1'
